=== edubossa/JAX-WS-2.0/xsd-jaxb-exemplo/src/xml/clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.globalcode.com.br/ae/clientes" elementFormDefault="qualified" > 
	
	<element name="clientes">
		<complexType>
			<sequence>
				<element name="cliente" maxOccurs="unbounded" >
					<complexType>
						<sequence>
							<element name="nome" type="string" />
							<choice>
								<element name="idade" type="int" minOccurs="0" />
								<element name="dataNascimento"  minOccurs="0" >
									<complexType>
										<attribute name="dia" use="required" type="int" />
										<attribute name="mes" use="required" type="int"  />
										<attribute name="ano" use="required" type="int"  />
									</complexType>
								</element> 
							</choice>	
							<element name="email" minOccurs="0" maxOccurs="unbounded" type="string" />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>	
	
</schema>

=== edubossa/JAX-WS-2.0/xsd-jaxb-exemplo/src/xml/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns="http://www.globalcode.com.br/ae/clientes" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.globalcode.com.br/ae/clientes clientes.xsd" >
	
	<cliente>
		<nome>Eduardo Wallace</nome>
		<dataNascimento dia="12" mes="12" ano="83" /> 
		<email>edubossa@gmail.com</email>
	</cliente>
	
	<cliente>
		<nome>Juca da Silva</nome>
		<idade>23</idade>
		<email>juca1@gmail.com</email>
		<email>juca2@gmail.com</email>
		<email>juca3@gmail.com</email>
	</cliente>
	
</clientes>
