=== edubossa/JAX-WS-2.0/xsd-jaxb-exemplo/src/xml/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.globalcode.com.br/ae/pedidos"
            xmlns:gc="http://www.globalcode.com.br/ae/pedidos"
            elementFormDefault="qualified">
                
    <!-- definicao do elemento raiz -->
    <xsd:element name="pedido" type="gc:pedido" />
    
    <!-- definicoes dos tipos complexos utilizados -->
    <xsd:complexType name="pedido">
        <xsd:sequence>
            <xsd:element name="cliente" type="gc:cliente" />
            <xsd:element name="item" type="gc:item" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="numero" type="xsd:int"/>
    </xsd:complexType>
 
    <xsd:complexType name="item">
        <xsd:sequence>
            <xsd:element name="quantidade" type="xsd:int"/>
            <xsd:element name="produto" type="gc:produto"/>
        </xsd:sequence>
    </xsd:complexType>    
    
    <xsd:complexType name="produto">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:int"/>
            <xsd:element name="nome" type="xsd:string"/>
            <xsd:element name="preco" type="xsd:double"/>
            <xsd:element name="marca" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="cliente">
        <xsd:sequence>
            <xsd:element name="nome" type="xsd:string"></xsd:element>
            <xsd:element name="endereco" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== edubossa/JAX-WS-2.0/xsd-jaxb-exemplo/src/xml/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido numero="1000"
        xmlns = "http://www.globalcode.com.br/ae/pedidos"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.globalcode.com.br/ae/pedidos pedidos.xsd">
    <cliente>
        <nome>Jos√© da Silva</nome>
        <endereco>Rua das Camelias, 320</endereco>
    </cliente>
    <item>
        <quantidade>1</quantidade>
        <produto>
            <id>311</id>
            <nome>Camera DC 510</nome>
            <preco>1500</preco>
            <marca>Sony</marca>
        </produto>
    </item>
    <item>
        <quantidade>2</quantidade>
        <produto>
            <id>312</id>
            <nome>HD 80GB</nome>
            <preco>400</preco>
            <marca>Samsung</marca>
        </produto>
    </item>
</pedido>
